spring:
  application:
    name: config
server:
  port: 8082
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  service-url:
    defaultZone: http://localhost:8001/eureka/
