spring:
  application:
    name: oss-server
server:
  port: 8086
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  service-url:
    defaultZone: http://localhost:8001/eureka/