spring:
  application:
    name: cache-server
  boot:
    admin:
      client:
        url: http://localhost:8088
server:
  port: 8081
eureka:
  service-url:
    defaultZone: http://localhost:8001/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"





