spring:
  application:
    name: oss
server:
  port: 8086
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    hostname: ${spring.cloud.client.ip-address}
    ip-address: localhost
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/