spring:
  application:
    name: operate-server
server:
  port: 8085
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  service-url:
    defaultZone: http://localhost:8001/eureka/